version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradio_app
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
